/* Distinct building sprites (front elevation) and weather effects.
   Each building is a single pixel sprite with a unique silhouette + signage.
   They're stored at native pixel size and rendered at scale 2-3 in the city.
*/

(function () {
  const { PixelSprite } = window;

  // Palette helpers used across multiple buildings
  // Direction can re-skin via CSS vars; for clarity each building has explicit colors.

  // 1. CAFE PIXEL — short corner cafe with awning + chimney + neon "COFFEE"
  const B_CAFE = {
    name: 'CAFE PIXEL', label: 'cafe',
    sprite: `
.............CC.............
............CCCC............
.............CC.............
.............CC.............
....AAAAAAAAAAAAAAAAAA......
...AAAAAAAAAAAAAAAAAAAA.....
..MMMMMMMMMMMMMMMMMMMMMM....
..MRRRMMMMMRRRMMMMMRRRMM....
..MRRRMMMMMRRRMMMMMRRRMM....
..MMMMMMMMMMMMMMMMMMMMMM....
..AA##AA##AA##AA##AA##AA....
..A####A####A####A####AA....
..MWWWMMWWWMMWWWMMWWWMMM....
..MWWWMMNNNMMWWWMMWWWMMM....
..MWWWMMNNNMMWWWMMWWWMMM....
..MWWWMMNNNMMWWWMMWWWMMM....
..PPPPPPPPPPPPPPPPPPPPPP....
..PYYYPYYYPYYYPYYYPYYYPP....
..PPPPPPPPPPPPPPPPPPPPPP....
.PPPPPPPPPPPPPPPPPPPPPPPP...
`,
    palette: {
      C: '#4a2a1a', // chimney smoke vent
      A: '#dc2626', // awning red
      M: '#3a2820', // wall warm brown
      R: '#fcd34d', // window warm
      '#': '#fbbf24', // awning stripe
      W: '#a78bfa', // window cool
      N: '#0a0524', // door
      P: '#0a0524', // base
      Y: '#fbbf24', // sidewalk light
    },
  };

  // 2. STUDY HALL — clock tower, tall narrow stone building
  const B_STUDY = {
    name: 'STUDY HALL', label: 'study',
    sprite: `
........YYYYYYYY........
.......YY......YY.......
......YY..AAAA..YY......
.....YY..AHHHHA..YY.....
....YYYYAHHHHHHAYYYY....
....SSSSSSSSSSSSSSS.....
....S..............S....
....S.RR..RR..RR..RR....
....S.RR..RR..RR..RRS...
....S..............S....
....S.RR..RR..RR..RRS...
....S.RR..RR..RR..RRS...
....S..............S....
....S.NN..NN..NN..NNS...
....S.NN..NN..NN..NNS...
....SBBBBBBBBBBBBBBBS...
....SBBBBBOOOOBBBBBSS...
....SBBBBBOOOOBBBBBBS...
....BBBBBBBBBBBBBBBBBB..
....BBBBBBBBBBBBBBBBBB..
`,
    palette: {
      Y: '#a78bfa',     // tower roof purple
      A: '#fcd34d',     // clock face
      H: '#0a0524',     // clock hand
      S: '#7c6f9e',     // stone
      R: '#fef9c3',     // warm windows
      N: '#a78bfa',     // upper purple windows
      B: '#5a4a7a',     // base stone
      O: '#fcd34d',     // door warm light
    },
  };

  // 3. LOFI BAR — dome on top, neon sign, jazzy
  const B_LOFI = {
    name: 'LOFI BAR', label: 'lofi',
    sprite: `
.........MMMMMM..........
........MM####MM.........
.......MM######MM........
......MM########MM.......
.....MMMMMMMMMMMMMM......
.....MMMMMMMMMMMMMM......
....MNNNNNNNNNNNNNNM.....
....MN##NN######NN#NM....
....MN##NN######NN#NM....
....MNNNNNNNNNNNNNNM.....
....MEEEEEEEEEEEEEEM.....
....ME##EE######EE##M....
....ME##EE######EE##M....
....MEEEEEEEEEEEEEEM.....
....MMMMMMMMMMMMMMMMM....
....M$$$$$$$$$$$$$$$M....
....M$LOFI$BAR$LIVE$M....
....M$$$$$$$$$$$$$$$M....
....MNNNNNNNNNNNNNNNM....
....MNNDDDNNDDDNNDDDM....
....MBBBBBBBBBBBBBBBM....
`,
    palette: {
      M: '#3a1a4a', '#': '#22d3ee', E: '#1a0d3d',
      N: '#5a2a6a', $: '#ec4899', D: '#fcd34d',
      B: '#0a0524', L: '#ec4899',
    },
  };

  // 4. PIXEL ARCADE — neon ARCADE sign, blocky retro
  const B_ARCADE = {
    name: 'PIXEL ARCADE', label: 'arcade',
    sprite: `
.MMMMMMMMMMMMMMMMMMMMMM.
.M####################M.
.M#AARCADEAARRRAACAA##M.
.M####################M.
.MMMMMMMMMMMMMMMMMMMMMM.
.MNNNNNNNNNNNNNNNNNNNNM.
.MNYYNNYYNNYYNNYYNNYYNM.
.MNYYNNYYNNYYNNYYNNYYNM.
.MNNNNNNNNNNNNNNNNNNNNM.
.MNCCCNNCCCNNCCCNNCCCNM.
.MNCCCNNCCCNNCCCNNCCCNM.
.MNNNNNNNNNNNNNNNNNNNNM.
.MNRRRNNRRRNNRRRNNRRRNM.
.MNRRRNNRRRNNRRRNNRRRNM.
.MNNNNNNNNNNNNNNNNNNNNM.
.MNNNNNNNDDDDDNNNNNNNNM.
.MNNNNNNNDOODNNNNNNNNNM.
.MBBBBBBBBBBBBBBBBBBBBM.
`,
    palette: {
      M: '#1a0d3d', '#': '#22d3ee', A: '#ec4899',
      R: '#f0abfc', C: '#fcd34d', Y: '#22d3ee',
      N: '#0a0524', D: '#1a0d3d', O: '#fcd34d',
      B: '#0a0524',
    },
  };

  // 5. NEKO RAMEN — lanterns, sloped tile roof
  const B_RAMEN = {
    name: 'NEKO RAMEN', label: 'ramen',
    sprite: `
.....RRRRRRRRRRRRR......
....RRRRRRRRRRRRRRR.....
...RRRRRRRRRRRRRRRRR....
..RRRRRRRRRRRRRRRRRRR...
..RRRRRRRRRRRRRRRRRRR...
...PPPPPPPPPPPPPPPPP....
....OOOOOOOOOOOOOOO.....
....OYO.OYO.OYO.OYO.....
....OYO.OYO.OYO.OYO.....
....OOO.OOO.OOO.OOO.....
...MMMMMMMMMMMMMMMMM....
...M$NEKO$RAMEN$LIT$M...
...MMMMMMMMMMMMMMMMMM...
...MWWMMWWMMWWMMWWMMM...
...MWNMMWWMMWWMMWNMMM...
...MWWMMWWMMWWMMWWMMM...
...MMMMMDDDDDMMMMMMMM...
...MMMMMDOODDMMMMMMMM...
...BBBBBBBBBBBBBBBBBB...
`,
    palette: {
      R: '#7c1d3a',    // tile roof
      P: '#0a0524',
      O: '#fbbf24',    // lanterns
      Y: '#dc2626',
      M: '#fef9c3',    // wall cream
      $: '#dc2626',    // sign red
      W: '#0a0524',    // window dark
      N: '#fef9c3',    // window highlight
      D: '#7c1d3a',    // door frame
      B: '#0a0524',
    },
  };

  // 6. LIBRARY — classical columns, dome
  const B_LIBRARY = {
    name: 'LIBRARY', label: 'library',
    sprite: `
..........DD..........
.........DDDD.........
........DDDDDD........
.......DDDDDDDD.......
......DDPPPPPPDD......
....SSSPPPPPPPPSS.....
....SSSSSSSSSSSSS.....
...SSAAAAAAAAAAASS....
...SSAAAAAAAAAAASS....
...SSCC.CC.CC.CCSS....
...SSCC.CC.CC.CCSS....
...SSCC.CC.CC.CCSS....
...SSCC.CC.CC.CCSS....
...SSCC.CC.CC.CCSS....
...SSCC.CC.CC.CCSS....
...SSCC.CC.CC.CCSS....
...SSSSSSSSSSSSSSS....
...SSSSDDDDDDDSSSSS...
...SSSSDOOOODSSSSSS...
...BBBBBBBBBBBBBBBB...
`,
    palette: {
      D: '#a78bfa',    // dome
      P: '#fcd34d',    // dome window
      S: '#d6c5e8',    // stone cream
      A: '#7c6f9e',    // pediment dark
      C: '#fcd34d',    // column gap (lit window)
      O: '#dc2626',    // door
      B: '#0a0524',
    },
  };

  // 7. COWORKING — glass tower with grid lights
  const B_CWORK = {
    name: 'COWORKING', label: 'cwork',
    sprite: `
.....TTTTTTTTTTTT......
.....TTTTTTTTTTTT......
.....G##G##G##G#G......
.....G##G##G##G#G......
.....GGGGGGGGGGGG......
.....G##G##G##G#G......
.....G##G##G##G#G......
.....GGGGGGGGGGGG......
.....G##G##G##G#G......
.....G##G##G##G#G......
.....GGGGGGGGGGGG......
.....G##G##G##G#G......
.....G##G##G##G#G......
.....GGGGGGGGGGGG......
.....G##G##G##G#G......
.....G##G##G##G#G......
.....GGGGGGGGGGGG......
.....NNNDDDDDDNNNN.....
.....NNNDOOODONNNN.....
.....BBBBBBBBBBBBB.....
`,
    palette: {
      T: '#22d3ee',
      G: '#1a0d3d',
      '#': '#67e8f9',
      N: '#0a0524',
      D: '#3a2a5a',
      O: '#fcd34d',
      B: '#0a0524',
    },
  };

  // 8. GALLERY — art deco with vertical neon
  const B_GAL = {
    name: 'GALLERY', label: 'gallery',
    sprite: `
..........$$..........
..........$$..........
..........$$..........
.........$$$$.........
.........$$$$.........
........MMMMMM........
.......MMNNMMMMM......
......MMNNNNMMMMM.....
.....MMNNNNNNMMMMM....
....MMMMMMMMMMMMMMM...
....MWWWMMWWWMMWWWM...
....MWWWMMWWWMMWWWM...
....MMMMMMMMMMMMMMM...
....MWWWMMWWWMMWWWM...
....MWWWMMWWWMMWWWM...
....MMMMMMMMMMMMMMM...
....MMMMM$$$$$MMMMM...
....MMMMM$ART$MMMMM...
....MMMMM$$$$$MMMMM...
....MMMMDDDDDDMMMMM...
....MMMMDOOOODMMMMM...
....BBBBBBBBBBBBBBB...
`,
    palette: {
      $: '#ec4899',
      M: '#2a1854',
      N: '#a78bfa',
      W: '#fbbf24',
      D: '#0a0524',
      O: '#22d3ee',
      B: '#0a0524',
    },
  };

  // 9. INK STORE — small craft store with sign
  const B_INK = {
    name: 'INK STORE', label: 'ink',
    sprite: `
......CCCCCCCCCC......
.....CCCCCCCCCCCC.....
....AAAAAAAAAAAAAA....
....AAAAAAAAAAAAAA....
...MMMMMMMMMMMMMMM....
...M$$$$$$$$$$$$$M....
...M$INK$STORE$$$M....
...M$$$$$$$$$$$$$M....
...MWWWMMWWWMMWWWM....
...MWWWMMWWWMMWWWM....
...MMMMMMMMMMMMMMM....
...MWWWMMWWWMMWWWM....
...MWWWMMWWWMMWWWM....
...MMMMMDDDDDMMMMM....
...MMMMMDOODOMMMMM....
...BBBBBBBBBBBBBBB....
`,
    palette: {
      C: '#fcd34d',
      A: '#6d28d9',
      M: '#3a2820',
      $: '#fbbf24',
      W: '#fef9c3',
      D: '#0a0524',
      O: '#fcd34d',
      B: '#0a0524',
    },
  };

  // 10. TOWER (background) — tall skyscraper
  const B_TOWER = {
    name: 'NEON TOWER', label: 'tower',
    sprite: `
......AA......
.....AAAA.....
....AAAAAA....
....BBBBBB....
....BWWBWB....
....BWWBWB....
....BBBBBB....
....BWBWWB....
....BWBWWB....
....BBBBBB....
....BWWBWB....
....BWWBWB....
....BBBBBB....
....BWBWWB....
....BWBWWB....
....BBBBBB....
....BWWBWB....
....BWWBWB....
....BBBBBB....
....BWBWWB....
....BWBWWB....
....BBBBBB....
....BWWBWB....
....BWWBWB....
....BBBBBB....
....BBBBBB....
`,
    palette: {
      A: '#ec4899', B: '#1a0d3d', W: '#fcd34d',
    },
  };

  const BUILDINGS = [
    { ...B_CAFE,    width: 28, scale: 3, key: 'cafe' },
    { ...B_STUDY,   width: 24, scale: 3, key: 'study' },
    { ...B_LOFI,    width: 25, scale: 3, key: 'lofi' },
    { ...B_ARCADE,  width: 24, scale: 3, key: 'arcade' },
    { ...B_RAMEN,   width: 24, scale: 3, key: 'ramen' },
    { ...B_LIBRARY, width: 22, scale: 3, key: 'library' },
    { ...B_CWORK,   width: 22, scale: 3, key: 'cwork' },
    { ...B_GAL,     width: 22, scale: 3, key: 'gallery' },
    { ...B_INK,     width: 22, scale: 3, key: 'ink' },
  ];

  // -------- Weather effects --------

  // Snow particles
  function Snow({ width, height, density = 1 }) {
    const ref = React.useRef(null);
    React.useEffect(() => {
      const c = ref.current; if (!c) return;
      c.width = width; c.height = height;
      const ctx = c.getContext('2d');
      const flakes = [];
      const n = Math.floor((width * height) / 5000 * density);
      for (let i = 0; i < n; i++) flakes.push({
        x: Math.random() * width,
        y: Math.random() * height,
        v: 0.4 + Math.random() * 0.6,
        d: Math.random() * Math.PI * 2,
        big: Math.random() < 0.15,
      });
      let raf;
      const tick = (t) => {
        ctx.clearRect(0, 0, width, height);
        ctx.fillStyle = '#f5f3ff';
        for (const f of flakes) {
          f.y += f.v;
          f.x += Math.sin((t + f.d * 1000) / 1200) * 0.4;
          if (f.y > height) { f.y = -2; f.x = Math.random() * width; }
          ctx.globalAlpha = 0.9;
          ctx.fillRect(Math.floor(f.x), Math.floor(f.y), 1, 1);
          if (f.big) ctx.fillRect(Math.floor(f.x) + 1, Math.floor(f.y), 1, 1);
        }
        ctx.globalAlpha = 1;
        raf = requestAnimationFrame(tick);
      };
      raf = requestAnimationFrame(tick);
      return () => cancelAnimationFrame(raf);
    }, [width, height, density]);
    return <canvas ref={ref} style={{ width, height, position: 'absolute', inset: 0, imageRendering: 'pixelated', pointerEvents: 'none' }} />;
  }

  // Drifting clouds (a few pixel cloud sprites floating across)
  function Clouds({ width, height, count = 4, color = 'rgba(245,243,255,0.7)' }) {
    const cloudSprite = `
.....CCCC.....
....CCCCCCC...
..CCCCCCCCCCC.
.CCCCCCCCCCCCC
.CCCCCCCCCCCC.
`;
    const [positions, setPositions] = React.useState(() =>
      Array.from({ length: count }, (_, i) => ({
        x: (i / count) * width + Math.random() * 100,
        y: 40 + Math.random() * (height * 0.35),
        v: 0.15 + Math.random() * 0.2,
        scale: 2 + Math.floor(Math.random() * 3),
      }))
    );
    React.useEffect(() => {
      let raf;
      const tick = () => {
        setPositions((ps) => ps.map((p) => {
          let x = p.x + p.v;
          if (x > width + 100) x = -150;
          return { ...p, x };
        }));
        raf = requestAnimationFrame(tick);
      };
      raf = requestAnimationFrame(tick);
      return () => cancelAnimationFrame(raf);
    }, [width]);
    return (
      <div style={{ position: 'absolute', inset: 0, pointerEvents: 'none', overflow: 'hidden' }}>
        {positions.map((p, i) => (
          <div key={i} style={{ position: 'absolute', left: p.x, top: p.y, opacity: 0.55 }}>
            <PixelSprite sprite={cloudSprite} palette={{ C: color }} scale={p.scale} />
          </div>
        ))}
      </div>
    );
  }

  // Lightning flash overlay
  function LightningFlash() {
    const [on, setOn] = React.useState(false);
    React.useEffect(() => {
      let stop = false;
      const loop = async () => {
        while (!stop) {
          await new Promise((r) => setTimeout(r, 6000 + Math.random() * 8000));
          if (stop) return;
          setOn(true);
          await new Promise((r) => setTimeout(r, 80));
          setOn(false);
          await new Promise((r) => setTimeout(r, 120));
          if (Math.random() < 0.6) { setOn(true); await new Promise((r) => setTimeout(r, 60)); setOn(false); }
        }
      };
      loop();
      return () => { stop = true; };
    }, []);
    return (
      <div style={{
        position: 'absolute', inset: 0,
        background: on ? 'rgba(245,243,255,0.4)' : 'transparent',
        pointerEvents: 'none', transition: 'background 80ms',
        zIndex: 2,
      }} />
    );
  }

  // Fog overlay
  function Fog({ width, height }) {
    return (
      <div style={{
        position: 'absolute', inset: 0,
        background: 'linear-gradient(180deg, rgba(167,139,250,0.05) 0%, rgba(167,139,250,0.15) 50%, rgba(7,4,26,0.4) 100%)',
        pointerEvents: 'none', zIndex: 2,
      }} />
    );
  }

  Object.assign(window, { BUILDINGS, Snow, Clouds, LightningFlash, Fog });
})();
