/* Distinct building sprites (front elevation) and weather effects.
 * Each building is a single pixel sprite with a unique silhouette + signage.
 * Ported from buildings.jsx — data only (weather components live in components/town).
 */

import type { Palette } from '@/lib/pixel-engine';

export interface BuildingDef {
  name: string;
  label: string;
  sprite: string;
  palette: Palette;
}

// 1. CAFE PIXEL — short corner cafe with awning + chimney + neon "COFFEE"
export const B_CAFE = {
  name: 'CAFE PIXEL', label: 'cafe',
  sprite: `
.............CC.............
............CCCC............
.............CC.............
.............CC.............
....AAAAAAAAAAAAAAAAAA......
...AAAAAAAAAAAAAAAAAAAA.....
..MMMMMMMMMMMMMMMMMMMMMM....
..MRRRMMMMMRRRMMMMMRRRMM....
..MRRRMMMMMRRRMMMMMRRRMM....
..MMMMMMMMMMMMMMMMMMMMMM....
..AA##AA##AA##AA##AA##AA....
..A####A####A####A####AA....
..MWWWMMWWWMMWWWMMWWWMMM....
..MWWWMMNNNMMWWWMMWWWMMM....
..MWWWMMNNNMMWWWMMWWWMMM....
..MWWWMMNNNMMWWWMMWWWMMM....
..PPPPPPPPPPPPPPPPPPPPPP....
..PYYYPYYYPYYYPYYYPYYYPP....
..PPPPPPPPPPPPPPPPPPPPPP....
.PPPPPPPPPPPPPPPPPPPPPPPP...
`,
  palette: {
    C: '#4a2a1a', // chimney smoke vent
    A: '#dc2626', // awning red
    M: '#3a2820', // wall warm brown
    R: '#fcd34d', // window warm
    '#': '#fbbf24', // awning stripe
    W: '#a78bfa', // window cool
    N: '#0a0524', // door
    P: '#0a0524', // base
    Y: '#fbbf24', // sidewalk light
  },
};

// 2. STUDY HALL — clock tower, tall narrow stone building
export const B_STUDY = {
  name: 'STUDY HALL', label: 'study',
  sprite: `
........YYYYYYYY........
.......YY......YY.......
......YY..AAAA..YY......
.....YY..AHHHHA..YY.....
....YYYYAHHHHHHAYYYY....
....SSSSSSSSSSSSSSS.....
....S..............S....
....S.RR..RR..RR..RR....
....S.RR..RR..RR..RRS...
....S..............S....
....S.RR..RR..RR..RRS...
....S.RR..RR..RR..RRS...
....S..............S....
....S.NN..NN..NN..NNS...
....S.NN..NN..NN..NNS...
....SBBBBBBBBBBBBBBBS...
....SBBBBBOOOOBBBBBSS...
....SBBBBBOOOOBBBBBBS...
....BBBBBBBBBBBBBBBBBB..
....BBBBBBBBBBBBBBBBBB..
`,
  palette: {
    Y: '#a78bfa',     // tower roof purple
    A: '#fcd34d',     // clock face
    H: '#0a0524',     // clock hand
    S: '#7c6f9e',     // stone
    R: '#fef9c3',     // warm windows
    N: '#a78bfa',     // upper purple windows
    B: '#5a4a7a',     // base stone
    O: '#fcd34d',     // door warm light
  },
};

// 3. LOFI BAR — dome on top, neon sign, jazzy
export const B_LOFI = {
  name: 'LOFI BAR', label: 'lofi',
  sprite: `
.........MMMMMM..........
........MM####MM.........
.......MM######MM........
......MM########MM.......
.....MMMMMMMMMMMMMM......
.....MMMMMMMMMMMMMM......
....MNNNNNNNNNNNNNNM.....
....MN##NN######NN#NM....
....MN##NN######NN#NM....
....MNNNNNNNNNNNNNNM.....
....MEEEEEEEEEEEEEEM.....
....ME##EE######EE##M....
....ME##EE######EE##M....
....MEEEEEEEEEEEEEEM.....
....MMMMMMMMMMMMMMMMM....
....M$$$$$$$$$$$$$$$M....
....M$LOFI$BAR$LIVE$M....
....M$$$$$$$$$$$$$$$M....
....MNNNNNNNNNNNNNNNM....
....MNNDDDNNDDDNNDDDM....
....MBBBBBBBBBBBBBBBM....
`,
  palette: {
    M: '#3a1a4a', '#': '#22d3ee', E: '#1a0d3d',
    N: '#5a2a6a', $: '#ec4899', D: '#fcd34d',
    B: '#0a0524', L: '#ec4899',
  },
};

// 4. PIXEL ARCADE — neon ARCADE sign, blocky retro
export const B_ARCADE = {
  name: 'PIXEL ARCADE', label: 'arcade',
  sprite: `
.MMMMMMMMMMMMMMMMMMMMMM.
.M####################M.
.M#AARCADEAARRRAACAA##M.
.M####################M.
.MMMMMMMMMMMMMMMMMMMMMM.
.MNNNNNNNNNNNNNNNNNNNNM.
.MNYYNNYYNNYYNNYYNNYYNM.
.MNYYNNYYNNYYNNYYNNYYNM.
.MNNNNNNNNNNNNNNNNNNNNM.
.MNCCCNNCCCNNCCCNNCCCNM.
.MNCCCNNCCCNNCCCNNCCCNM.
.MNNNNNNNNNNNNNNNNNNNNM.
.MNRRRNNRRRNNRRRNNRRRNM.
.MNRRRNNRRRNNRRRNNRRRNM.
.MNNNNNNNNNNNNNNNNNNNNM.
.MNNNNNNNDDDDDNNNNNNNNM.
.MNNNNNNNDOODNNNNNNNNNM.
.MBBBBBBBBBBBBBBBBBBBBM.
`,
  palette: {
    M: '#1a0d3d', '#': '#22d3ee', A: '#ec4899',
    R: '#f0abfc', C: '#fcd34d', Y: '#22d3ee',
    N: '#0a0524', D: '#1a0d3d', O: '#fcd34d',
    B: '#0a0524',
  },
};

// 5. NEKO RAMEN — lanterns, sloped tile roof
export const B_RAMEN = {
  name: 'NEKO RAMEN', label: 'ramen',
  sprite: `
.....RRRRRRRRRRRRR......
....RRRRRRRRRRRRRRR.....
...RRRRRRRRRRRRRRRRR....
..RRRRRRRRRRRRRRRRRRR...
..RRRRRRRRRRRRRRRRRRR...
...PPPPPPPPPPPPPPPPP....
....OOOOOOOOOOOOOOO.....
....OYO.OYO.OYO.OYO.....
....OYO.OYO.OYO.OYO.....
....OOO.OOO.OOO.OOO.....
...MMMMMMMMMMMMMMMMM....
...M$NEKO$RAMEN$LIT$M...
...MMMMMMMMMMMMMMMMMM...
...MWWMMWWMMWWMMWWMMM...
...MWNMMWWMMWWMMWNMMM...
...MWWMMWWMMWWMMWWMMM...
...MMMMMDDDDDMMMMMMMM...
...MMMMMDOODDMMMMMMMM...
...BBBBBBBBBBBBBBBBBB...
`,
  palette: {
    R: '#7c1d3a',    // tile roof
    P: '#0a0524',
    O: '#fbbf24',    // lanterns
    Y: '#dc2626',
    M: '#fef9c3',    // wall cream
    $: '#dc2626',    // sign red
    W: '#0a0524',    // window dark
    N: '#fef9c3',    // window highlight
    D: '#7c1d3a',    // door frame
    B: '#0a0524',
  },
};

// 6. LIBRARY — classical columns, dome
export const B_LIBRARY = {
  name: 'LIBRARY', label: 'library',
  sprite: `
..........DD..........
.........DDDD.........
........DDDDDD........
.......DDDDDDDD.......
......DDPPPPPPDD......
....SSSPPPPPPPPSS.....
....SSSSSSSSSSSSS.....
...SSAAAAAAAAAAASS....
...SSAAAAAAAAAAASS....
...SSCC.CC.CC.CCSS....
...SSCC.CC.CC.CCSS....
...SSCC.CC.CC.CCSS....
...SSCC.CC.CC.CCSS....
...SSCC.CC.CC.CCSS....
...SSCC.CC.CC.CCSS....
...SSCC.CC.CC.CCSS....
...SSSSSSSSSSSSSSS....
...SSSSDDDDDDDSSSSS...
...SSSSDOOOODSSSSSS...
...BBBBBBBBBBBBBBBB...
`,
  palette: {
    D: '#a78bfa',    // dome
    P: '#fcd34d',    // dome window
    S: '#d6c5e8',    // stone cream
    A: '#7c6f9e',    // pediment dark
    C: '#fcd34d',    // column gap (lit window)
    O: '#dc2626',    // door
    B: '#0a0524',
  },
};

// 7. COWORKING — glass tower with grid lights
export const B_CWORK = {
  name: 'COWORKING', label: 'cwork',
  sprite: `
.....TTTTTTTTTTTT......
.....TTTTTTTTTTTT......
.....G##G##G##G#G......
.....G##G##G##G#G......
.....GGGGGGGGGGGG......
.....G##G##G##G#G......
.....G##G##G##G#G......
.....GGGGGGGGGGGG......
.....G##G##G##G#G......
.....G##G##G##G#G......
.....GGGGGGGGGGGG......
.....G##G##G##G#G......
.....G##G##G##G#G......
.....GGGGGGGGGGGG......
.....G##G##G##G#G......
.....G##G##G##G#G......
.....GGGGGGGGGGGG......
.....NNNDDDDDDNNNN.....
.....NNNDOOODONNNN.....
.....BBBBBBBBBBBBB.....
`,
  palette: {
    T: '#22d3ee',
    G: '#1a0d3d',
    '#': '#67e8f9',
    N: '#0a0524',
    D: '#3a2a5a',
    O: '#fcd34d',
    B: '#0a0524',
  },
};

// 8. GALLERY — art deco with vertical neon
export const B_GAL = {
  name: 'GALLERY', label: 'gallery',
  sprite: `
..........$$..........
..........$$..........
..........$$..........
.........$$$$.........
.........$$$$.........
........MMMMMM........
.......MMNNMMMMM......
......MMNNNNMMMMM.....
.....MMNNNNNNMMMMM....
....MMMMMMMMMMMMMMM...
....MWWWMMWWWMMWWWM...
....MWWWMMWWWMMWWWM...
....MMMMMMMMMMMMMMM...
....MWWWMMWWWMMWWWM...
....MWWWMMWWWMMWWWM...
....MMMMMMMMMMMMMMM...
....MMMMM$$$$$MMMMM...
....MMMMM$ART$MMMMM...
....MMMMM$$$$$MMMMM...
....MMMMDDDDDDMMMMM...
....MMMMDOOOODMMMMM...
....BBBBBBBBBBBBBBB...
`,
  palette: {
    $: '#ec4899',
    M: '#2a1854',
    N: '#a78bfa',
    W: '#fbbf24',
    D: '#0a0524',
    O: '#22d3ee',
    B: '#0a0524',
  },
};

// 9. INK STORE — small craft store with sign
export const B_INK = {
  name: 'INK STORE', label: 'ink',
  sprite: `
......CCCCCCCCCC......
.....CCCCCCCCCCCC.....
....AAAAAAAAAAAAAA....
....AAAAAAAAAAAAAA....
...MMMMMMMMMMMMMMM....
...M$$$$$$$$$$$$$M....
...M$INK$STORE$$$M....
...M$$$$$$$$$$$$$M....
...MWWWMMWWWMMWWWM....
...MWWWMMWWWMMWWWM....
...MMMMMMMMMMMMMMM....
...MWWWMMWWWMMWWWM....
...MWWWMMWWWMMWWWM....
...MMMMMDDDDDMMMMM....
...MMMMMDOODOMMMMM....
...BBBBBBBBBBBBBBB....
`,
  palette: {
    C: '#fcd34d',
    A: '#6d28d9',
    M: '#3a2820',
    $: '#fbbf24',
    W: '#fef9c3',
    D: '#0a0524',
    O: '#fcd34d',
    B: '#0a0524',
  },
};

// 10. TOWER (background) — tall skyscraper
export const B_TOWER = {
  name: 'NEON TOWER', label: 'tower',
  sprite: `
......AA......
.....AAAA.....
....AAAAAA....
....BBBBBB....
....BWWBWB....
....BWWBWB....
....BBBBBB....
....BWBWWB....
....BWBWWB....
....BBBBBB....
....BWWBWB....
....BWWBWB....
....BBBBBB....
....BWBWWB....
....BWBWWB....
....BBBBBB....
....BWWBWB....
....BWWBWB....
....BBBBBB....
....BWBWWB....
....BWBWWB....
....BBBBBB....
....BWWBWB....
....BWWBWB....
....BBBBBB....
....BBBBBB....
`,
  palette: {
    A: '#ec4899', B: '#1a0d3d', W: '#fcd34d',
  },
};

export interface BuildingPlacement extends BuildingDef { width: number; scale: number; key: string; }
export const BUILDINGS: BuildingPlacement[] = [
  { ...B_CAFE,    width: 28, scale: 3, key: 'cafe' },
  { ...B_STUDY,   width: 24, scale: 3, key: 'study' },
  { ...B_LOFI,    width: 25, scale: 3, key: 'lofi' },
  { ...B_ARCADE,  width: 24, scale: 3, key: 'arcade' },
  { ...B_RAMEN,   width: 24, scale: 3, key: 'ramen' },
  { ...B_LIBRARY, width: 22, scale: 3, key: 'library' },
  { ...B_CWORK,   width: 22, scale: 3, key: 'cwork' },
  { ...B_GAL,     width: 22, scale: 3, key: 'gallery' },
  { ...B_INK,     width: 22, scale: 3, key: 'ink' },
];
